package me.ridog.valentine.pojo.auto;

import java.util.Date;

public class Content {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column valentine_contents.cid
     *
     * @mbggenerated
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column valentine_contents.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column valentine_contents.slug
     *
     * @mbggenerated
     */
    private String slug;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column valentine_contents.created
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column valentine_contents.modified
     *
     * @mbggenerated
     */
    private Date modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column valentine_contents.authorId
     *
     * @mbggenerated
     */
    private Integer authorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column valentine_contents.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column valentine_contents.allowComment
     *
     * @mbggenerated
     */
    private Integer allowcomment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column valentine_contents.text
     *
     * @mbggenerated
     */
    private String text;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column valentine_contents.cid
     *
     * @return the value of valentine_contents.cid
     * @mbggenerated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column valentine_contents.cid
     *
     * @param cid the value for valentine_contents.cid
     * @mbggenerated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column valentine_contents.title
     *
     * @return the value of valentine_contents.title
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column valentine_contents.title
     *
     * @param title the value for valentine_contents.title
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column valentine_contents.slug
     *
     * @return the value of valentine_contents.slug
     * @mbggenerated
     */
    public String getSlug() {
        return slug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column valentine_contents.slug
     *
     * @param slug the value for valentine_contents.slug
     * @mbggenerated
     */
    public void setSlug(String slug) {
        this.slug = slug == null ? null : slug.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column valentine_contents.created
     *
     * @return the value of valentine_contents.created
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column valentine_contents.created
     *
     * @param created the value for valentine_contents.created
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column valentine_contents.modified
     *
     * @return the value of valentine_contents.modified
     * @mbggenerated
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column valentine_contents.modified
     *
     * @param modified the value for valentine_contents.modified
     * @mbggenerated
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column valentine_contents.authorId
     *
     * @return the value of valentine_contents.authorId
     * @mbggenerated
     */
    public Integer getAuthorid() {
        return authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column valentine_contents.authorId
     *
     * @param authorid the value for valentine_contents.authorId
     * @mbggenerated
     */
    public void setAuthorid(Integer authorid) {
        this.authorid = authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column valentine_contents.status
     *
     * @return the value of valentine_contents.status
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column valentine_contents.status
     *
     * @param status the value for valentine_contents.status
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column valentine_contents.allowComment
     *
     * @return the value of valentine_contents.allowComment
     * @mbggenerated
     */
    public Integer getAllowcomment() {
        return allowcomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column valentine_contents.allowComment
     *
     * @param allowcomment the value for valentine_contents.allowComment
     * @mbggenerated
     */
    public void setAllowcomment(Integer allowcomment) {
        this.allowcomment = allowcomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column valentine_contents.text
     *
     * @return the value of valentine_contents.text
     * @mbggenerated
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column valentine_contents.text
     *
     * @param text the value for valentine_contents.text
     * @mbggenerated
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }
}