package me.ridog.valentine.mapper.auto;

import me.ridog.valentine.pojo.auto.Meta;

public interface MetaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table valentine_Meta
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table valentine_Meta
     *
     * @mbggenerated
     */
    int insert(Meta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table valentine_Meta
     *
     * @mbggenerated
     */
    int insertSelective(Meta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table valentine_Meta
     *
     * @mbggenerated
     */
    Meta selectByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table valentine_Meta
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Meta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table valentine_Meta
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Meta record);
}